/**
 * Локальні переклади для всіх слів 24 вбудованих текстів.
 * Вони використовуються раніше за зовнішній перекладач.
 */
export const cardGlossary: Record<string, string> = {
  "en-uk:a": "неозначений артикль",
  "en-uk:about": "про",
  "en-uk:above": "вище",
  "en-uk:accidentally": "випадково",
  "en-uk:across": "через; навпроти; по всій",
  "en-uk:adding": "додавання",
  "en-uk:address": "адреса",
  "en-uk:adds": "додає",
  "en-uk:after": "після",
  "en-uk:afternoon": "післяобідній час; друга половина дня",
  "en-uk:again": "знову",
  "en-uk:ago": "тому",
  "en-uk:air": "повітря",
  "en-uk:airport": "аеропорт",
  "en-uk:album": "альбом",
  "en-uk:almost": "майже",
  "en-uk:alone": "наодинці",
  "en-uk:along": "уздовж; разом із",
  "en-uk:always": "завжди",
  "en-uk:amir": "Амір",
  "en-uk:an": "неозначений артикль",
  "en-uk:and": "та",
  "en-uk:anna": "Анна",
  "en-uk:anonymous": "анонімний",
  "en-uk:another": "ще один",
  "en-uk:anymore": "більше",
  "en-uk:anyone": "будь-хто",
  "en-uk:anything": "що завгодно",
  "en-uk:apartment": "квартира",
  "en-uk:appeared": "з'явився",
  "en-uk:apple": "яблуко",
  "en-uk:apples": "яблука",
  "en-uk:arrived": "прибув",
  "en-uk:arrives": "прибуває",
  "en-uk:as": "як",
  "en-uk:asked": "запитав",
  "en-uk:asking": "запитуючи",
  "en-uk:asks": "запитує",
  "en-uk:at": "на",
  "en-uk:attention": "увага",
  "en-uk:attic": "горище",
  "en-uk:autumn": "осінь",
  "en-uk:away": "подалі",
  "en-uk:back": "назад",
  "en-uk:bakery": "пекарня",
  "en-uk:balcony": "балкон",
  "en-uk:ball": "м'яч",
  "en-uk:band": "гурт",
  "en-uk:bars": "бари",
  "en-uk:basket": "кошик",
  "en-uk:be": "бути",
  "en-uk:became": "став",
  "en-uk:because": "тому що",
  "en-uk:become": "стати",
  "en-uk:becomes": "стає",
  "en-uk:been": "був",
  "en-uk:before": "перед; до; раніше; до того, як",
  "en-uk:began": "почався",
  "en-uk:begin": "почати",
  "en-uk:beginning": "початок",
  "en-uk:behind": "позаду",
  "en-uk:bell": "дзвінок",
  "en-uk:ben": "Бен",
  "en-uk:ben's": "Бена",
  "en-uk:bench": "лавка",
  "en-uk:benches": "лавки",
  "en-uk:beside": "поруч із",
  "en-uk:best": "найкращий",
  "en-uk:between": "між",
  "en-uk:bicycle": "велосипед",
  "en-uk:big": "великий",
  "en-uk:birds": "птахи",
  "en-uk:birthday": "день народження",
  "en-uk:blank": "порожній; незаповнений; бланк",
  "en-uk:blue": "синій",
  "en-uk:blurry": "розмитий",
  "en-uk:book": "книжка",
  "en-uk:books": "книги",
  "en-uk:box": "коробка",
  "en-uk:boxes": "коробки",
  "en-uk:bread": "хліб",
  "en-uk:breathe": "дихати",
  "en-uk:bridge": "міст",
  "en-uk:bright": "яскравий",
  "en-uk:bring": "принести",
  "en-uk:brings": "приносить",
  "en-uk:broken": "поламаний",
  "en-uk:brother": "брат",
  "en-uk:brown": "коричневий",
  "en-uk:building": "будівля",
  "en-uk:bus": "автобус",
  "en-uk:busy": "зайнятий",
  "en-uk:but": "але",
  "en-uk:button": "кнопка",
  "en-uk:buys": "купує",
  "en-uk:by": "біля; поруч із; за допомогою; автор",
  "en-uk:caf": "кафе",
  "en-uk:cafe": "кафе",
  "en-uk:cafeteria": "кафетерій",
  "en-uk:cake": "торт, пиріг",
  "en-uk:calculations": "розрахунки",
  "en-uk:calls": "дзвонить; кличе; дзвінки",
  "en-uk:calm": "спокійний",
  "en-uk:camera": "фотоапарат, камера",
  "en-uk:can": "може",
  "en-uk:cannot": "не може; не вміє; не можна",
  "en-uk:careful": "обережний; уважний; ретельний",
  "en-uk:carefully": "ретельно",
  "en-uk:carpet": "килим",
  "en-uk:carrots": "морква",
  "en-uk:carrying": "несучи; переносячи; перевезення",
  "en-uk:case": "футляр; випадок; справа",
  "en-uk:cat": "кіт",
  "en-uk:cats": "коти",
  "en-uk:centre": "центр",
  "en-uk:chair": "стілець",
  "en-uk:chairs": "стільці",
  "en-uk:changed": "змінив; змінився; змінений",
  "en-uk:changes": "зміни",
  "en-uk:changing": "такий, що змінюється; мінливий; зміна",
  "en-uk:chart": "діаграма, графік",
  "en-uk:checks": "перевіряє; чеки",
  "en-uk:cheerful": "веселий",
  "en-uk:cheese": "сир",
  "en-uk:chestnut": "каштан",
  "en-uk:child": "дитина",
  "en-uk:children": "діти",
  "en-uk:choose": "вибрати",
  "en-uk:cinema": "кінотеатр; кіно",
  "en-uk:cinnamon": "кориця",
  "en-uk:city": "місто",
  "en-uk:clara": "Клара",
  "en-uk:class": "клас",
  "en-uk:classmate": "однокласник, однокласниця",
  "en-uk:classroom": "класна кімната",
  "en-uk:cleaning": "прибирання",
  "en-uk:clear": "чіткий",
  "en-uk:clearly": "очевидно",
  "en-uk:click": "натисніть",
  "en-uk:clocks": "годинники",
  "en-uk:close": "закрити",
  "en-uk:closely": "ретельно",
  "en-uk:closing": "закриття",
  "en-uk:clouds": "хмари",
  "en-uk:coast": "узбережжя",
  "en-uk:coffee": "кава",
  "en-uk:cold": "холодний",
  "en-uk:collar": "комір",
  "en-uk:colleague": "колега",
  "en-uk:collecting": "збір",
  "en-uk:collection": "колекція",
  "en-uk:colours": "кольори",
  "en-uk:comes": "приходить",
  "en-uk:comforted": "втішив; заспокоїв; втішений",
  "en-uk:coming": "прихід; наступний; той, що наближається",
  "en-uk:community": "спільнота",
  "en-uk:continuing": "продовжувати; продовжуючи; тривалий",
  "en-uk:conversation": "розмова",
  "en-uk:conversations": "розмови",
  "en-uk:copies": "копії",
  "en-uk:corner": "кут",
  "en-uk:could": "міг; могла; могли; міг би",
  "en-uk:council": "міська рада",
  "en-uk:countries": "країни",
  "en-uk:cousin": "кузен",
  "en-uk:crisp": "свіжий, бадьорий",
  "en-uk:crossed": "перейшов, перейшла; перетнув, перетнула",
  "en-uk:customers": "клієнти",
  "en-uk:dad": "тато",
  "en-uk:daniel": "Даніель",
  "en-uk:day": "день",
  "en-uk:days": "дні; днів",
  "en-uk:dear": "дорогий",
  "en-uk:decide": "вирішити",
  "en-uk:decides": "приймає рішення",
  "en-uk:decision": "рішення",
  "en-uk:delayed": "затриманий",
  "en-uk:deserved": "заслужений",
  "en-uk:desk": "стіл",
  "en-uk:did": "зробив",
  "en-uk:different": "інший",
  "en-uk:difficult": "складний",
  "en-uk:dinner": "вечеря",
  "en-uk:directions": "напрямки; вказівки",
  "en-uk:disappointed": "розчарований",
  "en-uk:discovered": "виявив; відкрив; знайшов",
  "en-uk:discuss": "обговорити",
  "en-uk:dish": "страва",
  "en-uk:displayed": "показав; відобразив; виставив",
  "en-uk:district": "район",
  "en-uk:does": "робить; виконує; допоміжне дієслово",
  "en-uk:dog": "собака",
  "en-uk:door": "двері",
  "en-uk:down": "вниз",
  "en-uk:draw": "малювати; тягнути",
  "en-uk:drawers": "шухляди",
  "en-uk:drawn": "намальований",
  "en-uk:drew": "малював; намалював (минулий час від draw)",
  "en-uk:drinks": "напої",
  "en-uk:driver": "водій",
  "en-uk:during": "під час",
  "en-uk:each": "кожен",
  "en-uk:early": "ранній; рано",
  "en-uk:easy": "легкий; простий; легко",
  "en-uk:elderly": "люди похилого віку",
  "en-uk:elena": "Олена",
  "en-uk:empty": "порожній",
  "en-uk:ends": "кінці",
  "en-uk:energy": "енергія",
  "en-uk:engineers": "інженери",
  "en-uk:english": "англійська",
  "en-uk:entered": "увійшов; ввів; введений",
  "en-uk:error": "помилка",
  "en-uk:eva": "Єва",
  "en-uk:evening": "вечір",
  "en-uk:every": "кожен",
  "en-uk:everyone": "всі",
  "en-uk:everything": "все",
  "en-uk:exchanged": "обміняв; обміняла; обмінялися",
  "en-uk:existed": "існував",
  "en-uk:explain": "пояснити",
  "en-uk:explained": "пояснив",
  "en-uk:explains": "пояснює",
  "en-uk:fame": "слава",
  "en-uk:family": "сім'я",
  "en-uk:famous": "відомий",
  "en-uk:favourite": "улюблений",
  "en-uk:feel": "відчувати",
  "en-uk:feeling": "відчуття",
  "en-uk:feels": "відчуває; почувається; відчувається",
  "en-uk:felt": "відчував",
  "en-uk:festival": "фестиваль",
  "en-uk:few": "кілька",
  "en-uk:film": "фільм",
  "en-uk:final": "остаточний",
  "en-uk:find": "знайти",
  "en-uk:finds": "виявляє",
  "en-uk:first": "перший; спершу; по-перше",
  "en-uk:fixed": "полагодив; закріпив; виправлений",
  "en-uk:flew": "пролетів",
  "en-uk:flights": "авіарейси",
  "en-uk:floors": "поверхи",
  "en-uk:flowers": "квіти",
  "en-uk:following": "наступний; подальший; після",
  "en-uk:food": "їжа",
  "en-uk:football": "футбол",
  "en-uk:for": "для; до; протягом; за",
  "en-uk:forget": "забути",
  "en-uk:forgot": "забув",
  "en-uk:found": "знайшов; знайшла; знайдений",
  "en-uk:four": "чотири",
  "en-uk:frame": "рама; кадр",
  "en-uk:fresh": "свіжий",
  "en-uk:fridge": "холодильник",
  "en-uk:friend": "друг, подруга",
  "en-uk:friendly": "дружній; привітний",
  "en-uk:friends": "друзі",
  "en-uk:from": "з",
  "en-uk:full": "повний",
  "en-uk:funny": "смішний",
  "en-uk:gains": "прибутки",
  "en-uk:garden": "сад",
  "en-uk:getting": "отримання; діставання; ставання",
  "en-uk:giant": "гігант",
  "en-uk:give": "дати",
  "en-uk:given": "дав; дала; даний; наданий; з огляду на",
  "en-uk:gives": "дає",
  "en-uk:go": "йти; їхати; піти",
  "en-uk:goes": "йде",
  "en-uk:good": "добрий; хороший; добре",
  "en-uk:grandfather": "дідусь",
  "en-uk:grandfather's": "дідова",
  "en-uk:grandma": "бабуся",
  "en-uk:grandma's": "бабусині",
  "en-uk:green": "зелений",
  "en-uk:greeted": "привітав; привітала; віталися",
  "en-uk:grey": "сірий",
  "en-uk:groceries": "продукти харчування",
  "en-uk:group": "група",
  "en-uk:guide": "гід; провідник; посібник; вести",
  "en-uk:had": "мав; мала; був; була; допоміжне дієслово",
  "en-uk:hale": "Гейл (прізвище); здоровий; міцний",
  "en-uk:hall": "зал",
  "en-uk:handle": "ручка",
  "en-uk:happy": "щасливий",
  "en-uk:has": "має",
  "en-uk:have": "мати",
  "en-uk:he": "він",
  "en-uk:hear": "чути",
  "en-uk:heavy": "важкий",
  "en-uk:held": "тримав; проводив; відбувся",
  "en-uk:helped": "допоміг",
  "en-uk:helpful": "корисний",
  "en-uk:helps": "допомагає",
  "en-uk:her": "її",
  "en-uk:herbs": "трави",
  "en-uk:herself": "себе; сама",
  "en-uk:hidden": "приховане",
  "en-uk:hiding": "приховування",
  "en-uk:hike": "похід",
  "en-uk:hill": "пагорб",
  "en-uk:him": "його",
  "en-uk:his": "його",
  "en-uk:hold": "утримувати",
  "en-uk:home": "дім",
  "en-uk:honest": "чесний",
  "en-uk:hours": "години",
  "en-uk:house": "будинок",
  "en-uk:houses": "будинки",
  "en-uk:hundred": "сто",
  "en-uk:i": "я",
  "en-uk:idea": "ідея",
  "en-uk:ideas": "ідеї",
  "en-uk:if": "якщо",
  "en-uk:imagined": "уявляв; уявляла; уявлений",
  "en-uk:immediately": "негайно",
  "en-uk:imperfect": "недосконалий",
  "en-uk:in": "в",
  "en-uk:incomplete": "неповний",
  "en-uk:inside": "всередині",
  "en-uk:instead": "натомість",
  "en-uk:interesting": "цікавий",
  "en-uk:into": "в",
  "en-uk:investigated": "досліджував; розслідував; досліджено",
  "en-uk:invites": "запрошує",
  "en-uk:irina": "Ірина",
  "en-uk:is": "є",
  "en-uk:it": "це",
  "en-uk:item": "пункт; предмет; позиція",
  "en-uk:its": "його; її",
  "en-uk:joined": "приєднався",
  "en-uk:journey": "подорож",
  "en-uk:journeys": "подорожі",
  "en-uk:juice": "сік",
  "en-uk:keeps": "зберігає",
  "en-uk:kept": "тримав; зберігав; продовжував",
  "en-uk:kind": "добрий; вид",
  "en-uk:kitchen": "кухня",
  "en-uk:knew": "знав",
  "en-uk:know": "знати",
  "en-uk:known": "відомий",
  "en-uk:knows": "знає",
  "en-uk:lamp": "лампа",
  "en-uk:landed": "приземлився",
  "en-uk:larger": "більший",
  "en-uk:last": "останній",
  "en-uk:late": "пізно",
  "en-uk:late-night": "пізно вночі",
  "en-uk:later": "пізніше",
  "en-uk:laugh": "сміятися; сміх",
  "en-uk:laughs": "сміється",
  "en-uk:leader": "керівник",
  "en-uk:leaf": "листок",
  "en-uk:learned": "навчився; навчилася; дізнався",
  "en-uk:leave": "залишати; йти; відпустка",
  "en-uk:leaves": "листя; залишає; вирушає",
  "en-uk:left": "ліворуч; лівий; залишив; пішов; поїхав",
  "en-uk:leo": "Лео",
  "en-uk:leo's": "Лео",
  "en-uk:less": "менше",
  "en-uk:letter": "лист",
  "en-uk:letters": "листи",
  "en-uk:librarian": "бібліотекар",
  "en-uk:library": "бібліотека",
  "en-uk:lift": "підйомник",
  "en-uk:light": "світло",
  "en-uk:like": "подобатися; як; наприклад",
  "en-uk:liked": "подобався; сподобався",
  "en-uk:likes": "подобається; любить; уподобання",
  "en-uk:lina": "ліна",
  "en-uk:line": "рядок",
  "en-uk:list": "список",
  "en-uk:listened": "слухав; слухала",
  "en-uk:listens": "слухає",
  "en-uk:london": "Лондон",
  "en-uk:long": "довгий",
  "en-uk:longer": "довше",
  "en-uk:look": "поглянь",
  "en-uk:looks": "виглядає",
  "en-uk:lost": "загублений",
  "en-uk:loud": "гучний; голосний",
  "en-uk:lunch": "обід",
  "en-uk:made": "зробив; зробила; виготовив; виготовлено",
  "en-uk:make": "зробити",
  "en-uk:makes": "робить",
  "en-uk:making": "робити; створювати; виготовлення",
  "en-uk:man": "чоловік",
  "en-uk:many": "багато",
  "en-uk:map": "карта",
  "en-uk:maps": "карти",
  "en-uk:maria": "Марія",
  "en-uk:market": "ринок",
  "en-uk:maya": "Майя",
  "en-uk:me": "мене; мені; мною",
  "en-uk:meet": "зустрітися",
  "en-uk:meeting": "зустріч; засідання",
  "en-uk:members": "учасники",
  "en-uk:memories": "спогади",
  "en-uk:memory": "пам'ять",
  "en-uk:mention": "згадувати; згадка",
  "en-uk:mia": "мія",
  "en-uk:mila": "Міла",
  "en-uk:mind": "розум; думка; заперечувати",
  "en-uk:minded": "заперечував; заперечувала; був проти",
  "en-uk:minutes": "хвилини",
  "en-uk:mistake": "помилка",
  "en-uk:models": "моделі",
  "en-uk:monday": "понеділок",
  "en-uk:money": "гроші",
  "en-uk:months": "місяці",
  "en-uk:more": "більше; ще; далі",
  "en-uk:morning": "ранок",
  "en-uk:most": "більшість; найбільший; найбільше",
  "en-uk:mother": "мати",
  "en-uk:move": "рухатися; переміщуватися",
  "en-uk:moved": "переїхав; перемістився; переміщений",
  "en-uk:mr": "пан",
  "en-uk:museum": "музей",
  "en-uk:music": "музика",
  "en-uk:my": "мій",
  "en-uk:nadia": "Надія",
  "en-uk:name": "ім'я",
  "en-uk:named": "назвав; названий; на ім'я",
  "en-uk:near": "поблизу",
  "en-uk:nearly": "майже",
  "en-uk:need": "потрібно",
  "en-uk:neighbour": "сусід, сусідка",
  "en-uk:neighbourhood": "район",
  "en-uk:neighbours": "сусіди",
  "en-uk:nervous": "нервовий",
  "en-uk:never": "ніколи",
  "en-uk:nevertheless": "проте",
  "en-uk:new": "новий",
  "en-uk:next": "наступний; потім",
  "en-uk:night": "ніч",
  "en-uk:no": "ні",
  "en-uk:nobody": "ніхто",
  "en-uk:nora": "Нора",
  "en-uk:not": "не",
  "en-uk:note": "записка, нотатка",
  "en-uk:notebook": "зошит; блокнот",
  "en-uk:nothing": "нічого",
  "en-uk:notice": "помічати; оголошення; повідомлення",
  "en-uk:notices": "помічає; оголошення; повідомлення",
  "en-uk:now": "зараз",
  "en-uk:o'clock": "година",
  "en-uk:objects": "об'єкти",
  "en-uk:of": "з",
  "en-uk:office": "офіс",
  "en-uk:oilcake": "жмих",
  "en-uk:old": "старий",
  "en-uk:on": "на",
  "en-uk:once-empty": "колись порожній",
  "en-uk:one": "один",
  "en-uk:online": "онлайн",
  "en-uk:only": "лише",
  "en-uk:open": "відкритий; відкрити",
  "en-uk:opened": "відкрив; відкрила; відкрилося; відкритий",
  "en-uk:opening": "відкриття",
  "en-uk:or": "або",
  "en-uk:ordinary": "звичайний",
  "en-uk:organise": "організувати",
  "en-uk:other": "інший; інше; інші",
  "en-uk:our": "наш",
  "en-uk:out": "назовні",
  "en-uk:outside": "зовні",
  "en-uk:over": "понад",
  "en-uk:own": "власний",
  "en-uk:owner": "власник",
  "en-uk:page": "сторінка",
  "en-uk:pages": "сторінки",
  "en-uk:paint": "фарбувати; малювати; фарба",
  "en-uk:painter": "художник",
  "en-uk:paintings": "картини",
  "en-uk:paper": "папір",
  "en-uk:park": "парк",
  "en-uk:part": "частина",
  "en-uk:party": "вечірка",
  "en-uk:passengers": "пасажири",
  "en-uk:path": "шлях",
  "en-uk:pattern": "закономірність, візерунок",
  "en-uk:pavel": "Павло",
  "en-uk:people": "люди",
  "en-uk:photo": "фотографія",
  "en-uk:photograph": "фотографія; фотографувати",
  "en-uk:photographed": "сфотографований",
  "en-uk:picnic": "пікнік",
  "en-uk:picture": "зображення",
  "en-uk:pictures": "фотографії",
  "en-uk:place": "місце",
  "en-uk:placed": "поклав; поставив; розмістив; розміщений",
  "en-uk:places": "місця",
  "en-uk:plan": "план",
  "en-uk:planned": "планував; спланував; запланований",
  "en-uk:planning": "планування",
  "en-uk:plans": "планує; плани",
  "en-uk:play": "грати; гра; вистава; відтворювати",
  "en-uk:player": "гравець",
  "en-uk:please": "будь ласка",
  "en-uk:poem": "вірш",
  "en-uk:poems": "вірші",
  "en-uk:postcard": "листівка",
  "en-uk:prague": "Прага",
  "en-uk:presentation": "презентація, виступ",
  "en-uk:pressing": "натискання; нагальний; пресування",
  "en-uk:problem": "проблема",
  "en-uk:professor": "професор",
  "en-uk:project": "проєкт",
  "en-uk:promised": "обіцяв",
  "en-uk:promises": "обіцяє; обіцянки",
  "en-uk:proposed": "запропонував; запропонувала; запропоновано",
  "en-uk:proud": "гордий",
  "en-uk:put": "покласти",
  "en-uk:puts": "кладе; ставить; надягає; поміщає",
  "en-uk:question": "питання",
  "en-uk:quiet": "тихий, спокійний",
  "en-uk:quieter": "тихіший; тихіше",
  "en-uk:radios": "радіоприймачі",
  "en-uk:rain": "дощ",
  "en-uk:rains": "йде дощ; дощі",
  "en-uk:rainy": "дощовий",
  "en-uk:rarely": "рідко",
  "en-uk:reaches": "досягає",
  "en-uk:read": "читати",
  "en-uk:reading": "читання",
  "en-uk:reads": "читає; читається",
  "en-uk:recipe": "рецепт",
  "en-uk:recorded": "записав; записала; зафіксований",
  "en-uk:recordings": "записи",
  "en-uk:red": "червоний",
  "en-uk:refused": "відмовився",
  "en-uk:remained": "залишився",
  "en-uk:remember": "пам’ятати; згадувати",
  "en-uk:remembers": "пам’ятає",
  "en-uk:reminder": "нагадування",
  "en-uk:repair": "ремонт; ремонтувати",
  "en-uk:repaired": "відремонтував; відремонтувала; відремонтували; відремонтований",
  "en-uk:repairs": "ремонтує; ремонт",
  "en-uk:replaced": "замінено",
  "en-uk:replacing": "заміна",
  "en-uk:resident's": "мешканця",
  "en-uk:retired": "на пенсії",
  "en-uk:return": "повернутися",
  "en-uk:returned": "повернувся",
  "en-uk:returns": "повертає; повернення",
  "en-uk:reviews": "відгуки",
  "en-uk:rides": "їде; катається; поїздки",
  "en-uk:river": "річка",
  "en-uk:road": "дорога",
  "en-uk:roads": "дороги",
  "en-uk:roof": "дах",
  "en-uk:room": "кімната",
  "en-uk:rosa": "роза",
  "en-uk:route": "маршрут",
  "en-uk:routine": "розпорядок; звичний порядок",
  "en-uk:run": "бігти; працювати",
  "en-uk:runs": "біжить; працює",
  "en-uk:said": "сказав",
  "en-uk:salty": "солоний",
  "en-uk:sam": "Сем",
  "en-uk:same": "той самий; однаковий",
  "en-uk:sat": "сидів; сиділа; сиділи",
  "en-uk:saturday": "субота",
  "en-uk:saying": "кажучи; висловлювання",
  "en-uk:says": "каже",
  "en-uk:school": "школа",
  "en-uk:sea": "море",
  "en-uk:search": "шукати; пошук",
  "en-uk:second": "другий",
  "en-uk:second-hand": "вживаний",
  "en-uk:see": "бачити; дивитися; див.",
  "en-uk:seeds": "насіння",
  "en-uk:sees": "бачить",
  "en-uk:sends": "надсилає",
  "en-uk:sentence": "речення",
  "en-uk:separate": "окремий",
  "en-uk:served": "обслуговував; служив; подав",
  "en-uk:several": "кілька",
  "en-uk:shared": "спільний; поділився; поділилася",
  "en-uk:she": "вона",
  "en-uk:shelf": "полиця",
  "en-uk:shelves": "полиці",
  "en-uk:ships": "кораблі",
  "en-uk:shoes": "взуття",
  "en-uk:shop": "магазин",
  "en-uk:shopping": "покупки",
  "en-uk:shops": "магазини",
  "en-uk:shore": "берег",
  "en-uk:short": "короткий",
  "en-uk:show": "показати",
  "en-uk:showed": "показав",
  "en-uk:shows": "показує",
  "en-uk:shutters": "жалюзі",
  "en-uk:sign": "знак",
  "en-uk:signs": "знаки",
  "en-uk:silence": "тиша",
  "en-uk:simple": "простий",
  "en-uk:sister": "сестра",
  "en-uk:sit": "сидіти",
  "en-uk:sketchbook": "альбом для ескізів",
  "en-uk:sky": "небо",
  "en-uk:sleepy": "сонний",
  "en-uk:slide": "слайд",
  "en-uk:slightly": "трохи",
  "en-uk:small": "невеликий",
  "en-uk:smallest": "найменший",
  "en-uk:smells": "пахне; запахи",
  "en-uk:smiles": "усміхається; посмішки",
  "en-uk:smiling": "усміхнений",
  "en-uk:smooth": "гладкий; рівний",
  "en-uk:snow": "сніг",
  "en-uk:so": "тож",
  "en-uk:soil": "ґрунт",
  "en-uk:songs": "пісні",
  "en-uk:soon": "незабаром",
  "en-uk:sounds": "звуки",
  "en-uk:soup": "суп",
  "en-uk:space": "простір; місце; пробіл",
  "en-uk:spain": "Іспанія",
  "en-uk:spends": "витрачає",
  "en-uk:spent": "витратив",
  "en-uk:spoke": "говорив; говорила; говорили; спиця",
  "en-uk:spring": "весна",
  "en-uk:square": "площа; квадрат",
  "en-uk:stall": "ринковий прилавок; ятка; кіоск",
  "en-uk:star": "зірка",
  "en-uk:starts": "починається",
  "en-uk:station": "станція",
  "en-uk:stay": "залишатися",
  "en-uk:stays": "залишається; перебування",
  "en-uk:steady": "стійкий; нерухомо; рівно",
  "en-uk:steep": "крутий",
  "en-uk:still": "все ще",
  "en-uk:stones": "камені",
  "en-uk:stood": "стояв",
  "en-uk:stopped": "зупинився",
  "en-uk:stories": "історії",
  "en-uk:storm": "буря",
  "en-uk:story": "історія, оповідання",
  "en-uk:strange": "дивний",
  "en-uk:street": "вулиця",
  "en-uk:streets": "вулиці",
  "en-uk:student": "учень, студент",
  "en-uk:students": "студенти",
  "en-uk:suggests": "пропонує",
  "en-uk:suitcase": "валіза",
  "en-uk:suited": "підходив; личив; влаштовував",
  "en-uk:summer": "літо",
  "en-uk:sun": "сонце",
  "en-uk:sunrise": "схід сонця",
  "en-uk:surprise": "сюрприз",
  "en-uk:survived": "вижив",
  "en-uk:tag": "бірка; жетон; тег",
  "en-uk:take": "взяти",
  "en-uk:takes": "бере; займає",
  "en-uk:talk": "розмовляти; розмова",
  "en-uk:taught": "навчав; навчив; викладав",
  "en-uk:tea": "чай",
  "en-uk:team": "команда",
  "en-uk:teenager": "підліток",
  "en-uk:teenagers": "підлітки",
  "en-uk:tell": "розповісти",
  "en-uk:tells": "повідомляє",
  "en-uk:than": "ніж",
  "en-uk:thank": "дякую",
  "en-uk:that": "що; той; та; те",
  "en-uk:the": "означений артикль",
  "en-uk:their": "їхній; їхня; їхнє; їхні",
  "en-uk:them": "їх",
  "en-uk:then": "тоді",
  "en-uk:there": "там",
  "en-uk:they": "вони",
  "en-uk:things": "речі",
  "en-uk:this": "цей; ця; це",
  "en-uk:three": "три",
  "en-uk:through": "через",
  "en-uk:throwing": "кидання",
  "en-uk:time": "час",
  "en-uk:tiny": "крихітний",
  "en-uk:tired": "втомлений",
  "en-uk:to": "до; показник інфінітива",
  "en-uk:toby": "Тобі",
  "en-uk:today": "сьогодні",
  "en-uk:together": "разом",
  "en-uk:told": "сказав; сказала; розповів; розповіла",
  "en-uk:tomorrow": "завтра",
  "en-uk:too": "теж; занадто; надто",
  "en-uk:tool": "інструмент",
  "en-uk:top": "верх; вершина; нагорі",
  "en-uk:toward": "у напрямку",
  "en-uk:town": "місто",
  "en-uk:traditional": "традиційний",
  "en-uk:trail": "стежка",
  "en-uk:train": "потяг",
  "en-uk:trains": "потяги",
  "en-uk:tram": "трамвай",
  "en-uk:translation": "переклад",
  "en-uk:travel": "подорожувати; подорож",
  "en-uk:travelled": "подорожував",
  "en-uk:tree": "дерево",
  "en-uk:tried": "спробував",
  "en-uk:trip": "подорож",
  "en-uk:turning": "поворот",
  "en-uk:twenty": "двадцять",
  "en-uk:two": "два",
  "en-uk:umbrella": "парасолька",
  "en-uk:under": "під",
  "en-uk:understands": "розуміє",
  "en-uk:unexpected": "несподіваний",
  "en-uk:unexpectedly": "несподівано",
  "en-uk:unfinished": "незавершений",
  "en-uk:university": "університет",
  "en-uk:until": "доки",
  "en-uk:up": "вгору",
  "en-uk:upstairs": "нагорі",
  "en-uk:us": "нас",
  "en-uk:use": "використовувати; користуватися; використання",
  "en-uk:used": "використаний; раніше; колись",
  "en-uk:useful": "корисний",
  "en-uk:usual": "звичайний",
  "en-uk:valley": "долина",
  "en-uk:valuable": "цінний",
  "en-uk:view": "вид; краєвид; переглядати",
  "en-uk:violin": "скрипка",
  "en-uk:visit": "відвідувати; візит",
  "en-uk:visited": "відвідав",
  "en-uk:visiting": "відвідувати; відвідування",
  "en-uk:visitors": "відвідувачі",
  "en-uk:voices": "голоси",
  "en-uk:volunteers": "волонтери",
  "en-uk:wait": "чекати; зачекати",
  "en-uk:waiting": "чекати; очікування",
  "en-uk:waits": "чекає",
  "en-uk:wake": "прокидатися; будити",
  "en-uk:wakes": "прокидається; будить",
  "en-uk:walk": "прогулянка; гуляти",
  "en-uk:walked": "йшов; йшла; гуляв; гуляла",
  "en-uk:walking": "ходьба; йдучи; гуляючи",
  "en-uk:walks": "ходить; прогулянки",
  "en-uk:want": "хотіти",
  "en-uk:wanted": "хотів; хотіла; бажаний; розшукується",
  "en-uk:wants": "хоче",
  "en-uk:warm": "теплий",
  "en-uk:was": "був; була; було",
  "en-uk:watch": "дивитися",
  "en-uk:watched": "дивився; дивилася; спостерігав; спостерігала",
  "en-uk:watches": "дивиться; годинники",
  "en-uk:water": "вода",
  "en-uk:wave": "махати; хвиля",
  "en-uk:way": "шлях; дорога; спосіб",
  "en-uk:we": "ми",
  "en-uk:wears": "носить",
  "en-uk:week": "тиждень",
  "en-uk:weekly": "щотижневий; щотижня",
  "en-uk:weeks": "тижнів",
  "en-uk:what": "що",
  "en-uk:when": "коли",
  "en-uk:whenever": "щоразу, коли; коли б не",
  "en-uk:where": "де",
  "en-uk:whether": "чи",
  "en-uk:which": "який",
  "en-uk:while": "тоді як",
  "en-uk:who": "хто",
  "en-uk:whole": "цілий; весь",
  "en-uk:why": "чому",
  "en-uk:will": "буду; будеш; буде; будемо; будете; будуть; майбутній час",
  "en-uk:wind": "вітер",
  "en-uk:window": "вікно",
  "en-uk:windows": "вікна",
  "en-uk:windy": "вітряний",
  "en-uk:winter": "зима",
  "en-uk:wishes": "бажає; побажання",
  "en-uk:with": "з",
  "en-uk:woman": "жінка",
  "en-uk:wooden": "дерев'яний",
  "en-uk:word": "слово",
  "en-uk:words": "слова",
  "en-uk:work": "робота",
  "en-uk:worked": "працював; працювала; працювали",
  "en-uk:worker": "працівник",
  "en-uk:workshop": "майстерня",
  "en-uk:worlds": "світи",
  "en-uk:write": "писати; написати",
  "en-uk:writes": "пише",
  "en-uk:writing": "писання; написання; письмо",
  "en-uk:written": "написано",
  "en-uk:wrote": "написав; написала",
  "en-uk:year": "рік",
  "en-uk:years": "роки",
  "en-uk:yellow": "жовтий",
  "en-uk:yesterday": "вчора",
  "en-uk:yet": "ще; поки що; однак",
  "en-uk:you": "ти; ви",
};
