import { cardGlossary } from "./card-glossary";

/**
 * Перевірений словник для частих та неоднозначних навчальних слів.
 * Ключ містить напрямок перекладу, щоб значення не змішувалися.
 */
export const glossary: Record<string, string> = {
  ...cardGlossary,
  "en-uk:morning": "ранок",
  "en-uk:walk": "прогулянка; гуляти",
  "en-uk:quiet": "тихий, спокійний",
  "en-uk:calm": "спокійний",
  "en-uk:street": "вулиця",
  "en-uk:home": "дім",
  "en-uk:park": "парк",
  "en-uk:dog": "собака",
  "en-uk:ball": "м'яч",
  "en-uk:bench": "лавка",
  "en-uk:tea": "чай",
  "en-uk:leaf": "листок",
  "en-uk:leaves": "листя; залишає; вирушає",
  "en-uk:wind": "вітер",
  "en-uk:class": "клас",
  "en-uk:classmate": "однокласник, однокласниця",
  "en-uk:student": "учень, студент",
  "en-uk:classroom": "класна кімната",
  "en-uk:library": "бібліотека",
  "en-uk:school": "школа",
  "en-uk:friend": "друг, подруга",
  "en-uk:music": "музика",
  "en-uk:rain": "дощ",
  "en-uk:rainy": "дощовий",
  "en-uk:football": "футбол",
  "en-uk:paper": "папір",
  "en-uk:city": "місто",
  "en-uk:road": "дорога",
  "en-uk:bicycle": "велосипед",
  "en-uk:station": "станція",
  "en-uk:basket": "кошик",
  "en-uk:bell": "дзвінок",
  "en-uk:note": "записка, нотатка",
  "en-uk:market": "ринок",
  "en-uk:apple": "яблуко",
  "en-uk:bread": "хліб",
  "en-uk:cheese": "сир",
  "en-uk:recipe": "рецепт",
  "en-uk:cake": "торт, пиріг",
  "en-uk:oilcake": "жмих",
  "en-uk:birthday": "день народження",
  "en-uk:letter": "лист",
  "en-uk:river": "річка",
  "en-uk:book": "книжка",
  "en-uk:read": "читати",
  "en-uk:story": "історія, оповідання",
  "en-uk:word": "слово",
  "en-uk:translation": "переклад",
  "en-uk:crisp": "свіжий, бадьорий",
  "en-uk:wake": "прокидатися; будити",
  "en-uk:wakes": "прокидається; будить",
  "en-uk:run": "бігти; працювати",
  "en-uk:runs": "біжить; працює",
  "en-uk:neighbour": "сусід, сусідка",
  "en-uk:train": "потяг",
  "en-uk:sea": "море",
  "en-uk:coast": "узбережжя",
  "en-uk:crossed": "перейшов, перейшла; перетнув, перетнула",
  "en-uk:window": "вікно",
  "en-uk:poem": "вірш",
  "en-uk:camera": "фотоапарат, камера",
  "en-uk:photograph": "фотографія; фотографувати",
  "en-uk:cafe": "кафе",
  "en-uk:hike": "похід",
  "en-uk:hill": "пагорб",
  "en-uk:valley": "долина",
  "en-uk:council": "міська рада",
  "en-uk:community": "спільнота",
  "en-uk:presentation": "презентація, виступ",
  "en-uk:chart": "діаграма, графік",
  "en-uk:pattern": "закономірність, візерунок",
  "en-uk:mistake": "помилка",
  "en-uk:airport": "аеропорт",
  "en-uk:suitcase": "валіза",
  "en-uk:driver": "водій",
  "en-uk:repair": "ремонт; ремонтувати",
  "en-uk:workshop": "майстерня",
  "en-uk:chair": "стілець",
  "en-uk:drew": "малював; намалював (минулий час від draw)",
  "en-uk:draw": "малювати; тягнути",

  "uk-en:книжка": "book",
  "uk-en:книга": "book",
  "uk-en:слово": "word",
  "uk-en:читати": "read",
  "uk-en:переклад": "translation",
  "uk-en:жмих": "oilcake; press cake",
  "uk-en:пиріг": "pie; cake",
  "uk-en:торт": "cake",
  "uk-en:це": "this; it",
  "uk-en:цей": "this",
  "uk-en:ця": "this",
  "uk-en:ці": "these",
  "uk-en:цього": "this; of this",
  "uk-en:того": "that; of that",
  "uk-en:тихий": "quiet",
  "uk-en:спокійний": "calm; quiet",
  "uk-en:прогулянка": "walk",
  "uk-en:сусід": "neighbour",
  "uk-en:сусідка": "neighbour",
  "uk-en:оповідання": "story",
  "uk-en:історія": "story; history",
  "uk-en:помилка": "mistake",
  "uk-en:бібліотека": "library",
  "uk-en:місто": "city",
  "uk-en:вулиця": "street",
  "uk-en:дім": "home; house",
  "uk-en:школа": "school",
  "uk-en:учень": "student; pupil",
  "uk-en:рецепт": "recipe",
  "uk-en:сад": "garden",
  "uk-en:потяг": "train",
  "uk-en:море": "sea",
  "uk-en:вікно": "window",
  "uk-en:камера": "camera",
  "uk-en:ремонт": "repair",
  "uk-en:стілець": "chair",
  "uk-en:спільнота": "community",
  "uk-en:малювати": "draw",
  "uk-en:малював": "drew; was drawing",
  "uk-en:намалював": "drew",
  "uk-en:друг": "friend",
  "uk-en:подруга": "friend",
  "uk-en:родина": "family",
  "uk-en:робота": "work; job",
};
